"""cpp-optimizer has no interactive environment tools.

The agent writes a final C++17 submission into the attempt workspace. The
scorer compiles and batch-evaluates that submission against hidden fixtures
generated by `materials/hidden/gen_cases.py`.
"""
