"""Adapter interface and shared data structures.

This is the extension point of the whole project: `AgentAdapter` is a
`Protocol`, not a base class, so plugging in a new agent means writing one
file that satisfies this shape and registering it — nothing else in
`backend.runner` / `backend.run_dispatch` needs to change. `ClaudeCodeAdapter`
and `CodexAdapter` are the reference implementations; `CustomCliAdapter`
(see `custom_cli.py`) is a generic, config-driven adapter for wiring up any
other CLI-based agent without writing Python at all.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Protocol

from ..wire.injection import WireInjection


def build_security_meta(
    *,
    execution_locus: str,
    permission_mode: str | None,
    workspace_root: str | None,
) -> dict[str, Any]:
    """Snapshot of how/where the agent actually ran.

    - execution_locus: e.g. "host", "docker-sandbox", "remote-host"
    - permission_mode: the literal approval/permission flag passed at launch
    - workspace_root: the directory boundary the agent was authorized to touch
    """
    return {
        "execution_locus": execution_locus,
        "permission_mode": permission_mode,
        "workspace_root": workspace_root,
    }


@dataclass
class McpServerSpec:
    """An MCP stdio entrypoint explicitly declared by a scenario's meta.yaml.

    Adapters translate this into whatever config shape the target CLI wants;
    they must never guess or synthesize a server from `env_name` alone.
    `cwd` is the directory the scenario's command should be resolved/run
    relative to.
    """

    name: str
    command: str
    args: tuple[str, ...] = ()
    cwd: str | None = None


@dataclass
class AdapterRunInput:
    """Minimal input for a single attempt.

    Deliberately not the full backend.models dataclass/Pydantic model —
    adapters should not depend on backend's internal schema.

    `session_token` is plaintext, generated by the runner and handed to the
    adapter. Adapters that expose it to the agent's tool-calling environment
    (e.g. via env vars for an MCP server) must never persist it to any
    durable channel.
    """

    attempt_id: str
    task_id: str
    task_prompt: str
    task_context: dict[str, Any]
    timeout_seconds: int
    env_name: str
    env_skill_id: str  # "lane/<env_name>"
    session_token: str  # plaintext, only used to authorize the MCP tool server
    env_base_url: str  # public address of the attempt server (agent-reachable)
    # Explicitly declared by the scenario's meta.yaml (`entrypoints.mcp`); an
    # empty tuple means the scenario provides no MCP server. Adapters must
    # not infer or fabricate a server from env_name.
    mcp_servers: tuple[McpServerSpec, ...] = ()
    # Wire observability injection (backend/wire/), merged by dispatch before
    # the adapter runs. Defaults to a no-op injection so adapters that don't
    # care about wire capture behave exactly as before it existed.
    wire_injection: WireInjection = field(default_factory=WireInjection)


def prompt_context(task_context: dict[str, Any]) -> dict[str, Any]:
    """Render task_context into what the agent actually sees.

    `uploaded_files` becomes a list of filenames under the agent's working
    directory (materials are already placed there by dispatch), never a host
    path. Shared across adapters so every agent gets the same prompt shape,
    keeping the comparison fair.
    """
    context = {
        k: v for k, v in task_context.items() if k != "uploaded_files" and not k.startswith("_")
    }
    uploaded = task_context.get("uploaded_files")
    if uploaded and isinstance(uploaded, list):
        names = [uf.get("name", "") for uf in uploaded if uf.get("name")]
        if names:
            context["input_files_in_workdir"] = names
    return context


@dataclass
class AdapterResult:
    attempt_id: str
    status: str
    external_refs: dict[str, Any] = field(default_factory=dict)
    error_code: str | None = None
    error_message: str | None = None
    events_count: int = 0
    last_event_at: str | None = None
    thinking_count: int = 0
    token_usage: dict[str, int] = field(default_factory=dict)
    duration_ms: int = 0
    security_meta: dict[str, Any] = field(default_factory=dict)


class AgentAdapter(Protocol):
    async def run(
        self,
        task: AdapterRunInput,
        env: Any,
        data_path: Path,
    ) -> AdapterResult:
        """Run one attempt.

        - Must handle its own timeout/failure classification; never raise
          (wrap crashes as `error_code`+`error_message` with a terminal
          `status`).
        - Writes `events.jsonl` / `thinking.jsonl` to
          `<data_path>/attempts/{attempt_id}/`.
        - Must NOT write the env DB or trace.jsonl — that's the attempt
          server's job, triggered by the agent's own tool calls.
        """
        ...
